version: "3.7"

services:
  postgres:
    image: postgres:15
    command: postgres -c 'max_connections=4'
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
#  pgbouncer-proxy:
#    image: haproxy
#    ports:
#      - "6432:6432"
#    volumes:
#      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
#    depends_on:
#      pgbouncer:
#        condition: service_started
#  pgbouncer:
#    image: bitnami/pgbouncer:1.20.1
#    deploy:
#        replicas: 10
#        endpoint_mode: dnsrr
#        restart_policy:
#            condition: on-failure
#    ports:
#      - target: 6432
#        protocol: tcp
#    environment:
#    - POSTGRESQL_HOST=postgres
#    - POSTGRESQL_PORT=5432
#    - POSTGRESQL_USERNAME=postgres
#    - POSTGRESQL_PASSWORD=postgres
#    - POSTGRESQL_DATABASE=postgres
#    - PGBOUNCER_DATABASE=postgres
#    - PGBOUNCER_AUTH_TYPE=trust
#    - PGBOUNCER_AUTH_USER=postgres
#    - PGBOUNCER_POOL_MODE=session
#    - PGBOUNCER_DEFAULT_POOL_SIZE=5
#    - PGBOUNCER_MAX_CLIENT_CONN=5
#    depends_on:
#      postgres:
#        condition: service_healthy
