// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: queries.sql

package queries

import (
	"context"
)

const getValue = `-- name: GetValue :one
SELECT $1::int FROM (SELECT pg_sleep($2)::void) AS t
`

type GetValueParams struct {
	Column1 int32
	PgSleep float64
}

func (q *Queries) GetValue(ctx context.Context, arg GetValueParams) (int32, error) {
	row := q.db.QueryRow(ctx, getValue, arg.Column1, arg.PgSleep)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
